<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sup_1</name>
   <tag></tag>
   <elementGuidId>3150a30a-eb02-473e-a306-dd90675ab0de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//sup[(text() = '1' or . = '1')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>.//*[@id='hero']/div[1]/div/div[2]/div[2]/div/p[1]/sup[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>sup</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hero&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row special-row&quot;]/div[@class=&quot;col-xs-12 col-sm-12 col-md-12 col-lg-6 right-rail pull-right&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;title&quot;]/p[1]/sup[1]</value>
   </webElementProperties>
</WebElementEntity>
